library: input

views: 
- name: spend_data_view
  engine: SPARK
  transformations:
  - as: readCollection
    operation: readCollection
    enforceSchema: true
    collection: data.collections.spend_data_coll
  - as: selectFields
    operation: selectFields
    source: readCollection
    foreach:
      columns:
      - Price Details
      type: "Common:String"
  outputDefinition:
    type: delimited