library: input

views: 
- name: spend_data_view
  engine: SPARK
  transformations:
  - as: readCollection
    operation: readCollection
    enforceSchema: true
  - as: readCollection1
    operation: readCollection
    enforceSchema: true
  - as: join
    operation: join
    left: readCollection
    right: readCollection1
    mode: FULL_OUTER
    mergeLeftAndRightKeys: true
  outputDefinition:
    type: delimited