library: View5

collections: 
- name: ppl_records_coll_a
  format: avro
  filePatterns:
  - /home/deuser/workspaces/dejpexistingsol/JP_15-JAN-25/common/avro8_dataset/ppl-5-records_wo_space.avro
  schema: ppl_records_wspace_schema_avro
schemas: 
- name: ppl_records_wspace_schema_avro
  columns:
  - name: Index
    typeID: Common:Integer
  - name: UserId
    typeID: Common:String
  - name: FirstName
    typeID: Common:String
  - name: LastName
    typeID: Common:String
  - name: Sex
    typeID: Common:String
  - name: Email
    typeID: Common:String
  - name: Phone
    typeID: Common:String
  - name: Dateofbirth
    typeID: Common:String
  - name: JobTitle
    typeID: Common:String
  - name: Age
    typeID: Common:Integer
  - name: Income
    typeID: Common:Long
  - name: TaxSubmitted
    typeID: Common:Long
views: 
- name: ppl_record_view_avro
  engine: SPARK
  transformations:
  - as: readCollection
    operation: readCollection
    enforceSchema: true
    collection: ppl_records_coll_a
  outputDefinition:
    type: avro8